application: youtify-search-stats
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /fakesetup
  script: main.py

- url: /entries
  script: main.py

- url: /
  script: main.py
